
export interface Course {
    id: string;
    title: string;
    description: string;
    duration: string;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    tags: string[];
    thumbnailUrl: string;
    courseUrl: string;
  }
  
  export const MOCK_COURSES: Course[] = [
    {
      id: 'professional-cloud-devops-engineer-certification',
      title: 'Professional Cloud DevOps Engineer Path',
      description: 'This learning path helps you advance your skills in site reliability engineering, CI/CD pipelines, and service management on Google Cloud.',
      duration: '40+ Hours',
      difficulty: 'Advanced',
      tags: ['DevOps', 'CI/CD', 'SRE', 'Certification'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.credly.com/org/google-cloud/badge/professional-cloud-devops-engineer-certification',
    },
    {
      id: 'create-and-manage-cloud-resources',
      title: 'Create and Manage Cloud Resources',
      description: 'Get hands-on practice with the foundational components of Google Cloud, including projects, IAM, networking, and Compute Engine.',
      duration: '8 Hours',
      difficulty: 'Beginner',
      tags: ['GCP', 'Admin', 'IAM'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/716',
    },
     {
      id: 'perform-foundational-infra-tasks',
      title: 'Perform Foundational Infrastructure Tasks',
      description: 'This is the introductory quest for those new to Google Cloud, providing hands-on practice with the most common services.',
      duration: '6 Hours',
      difficulty: 'Beginner',
      tags: ['GCP', 'Compute', 'Storage', 'Networking'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/676',
    },
    {
      id: 'set-up-and-configure-a-cloud-environment',
      title: 'Set up and Configure a Cloud Environment',
      description: 'Learn how to configure a cloud environment using the Google Cloud console and gcloud command-line tool, including projects and billing.',
      duration: '7 Hours',
      difficulty: 'Beginner',
      tags: ['GCP', 'Admin', 'Billing'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/654',
    },
    {
      id: 'automating-infrastructure-with-terraform',
      title: 'Automating Infrastructure with Terraform',
      description: 'Learn to use Terraform, the popular Infrastructure as Code (IaC) tool, to provision and manage Google Cloud resources efficiently and repeatably.',
      duration: '6 Hours',
      difficulty: 'Intermediate',
      tags: ['Terraform', 'IaC', 'DevOps', 'GCP'],
      thumbnailUrl: 'https://logodix.com/logo/1686066.png',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/756',
    },
    {
      id: 'build-and-secure-networks-in-google-cloud',
      title: 'Build and Secure Networks in Google Cloud',
      description: 'Explore Google Cloud\'s networking capabilities, from VPCs and subnets to firewalls and load balancing. A core skill for any cloud professional.',
      duration: '8 Hours',
      difficulty: 'Intermediate',
      tags: ['Networking', 'Security', 'VPC', 'GCP'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/748',
    },
     {
      id: 'ensure-access-and-identity-in-google-cloud',
      title: 'Ensure Access and Identity in Google Cloud',
      description: 'Master Identity and Access Management (IAM) in Google Cloud. Learn about roles, permissions, and service accounts to secure your cloud environment.',
      duration: '6 Hours',
      difficulty: 'Intermediate',
      tags: ['Security', 'IAM', 'GCP'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/625',
    },
    {
      id: 'getting-started-with-gke',
      title: 'Getting Started with Google Kubernetes Engine',
      description: 'Learn the fundamentals of GKE, including creating clusters, deploying containerized applications, and managing workloads with kubectl and Google Cloud Console.',
      duration: '7 Hours',
      difficulty: 'Intermediate',
      tags: ['GKE', 'Kubernetes', 'Containers', 'DevOps'],
      thumbnailUrl: 'https://cdn.qwiklabs.com/gFmqBw+OuxgbiL0lz4P6jAQ57ywaL4ecCKO4N4BIfgI=',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/747',
    },
     {
      id: 'architecting-with-google-compute-engine',
      title: 'Architecting with Google Compute Engine',
      description: 'Learn to design and deploy robust, scalable, and highly available solutions on Google Compute Engine, from VMs to load balancing.',
      duration: '12 Hours',
      difficulty: 'Intermediate',
      tags: ['GCP', 'Architecture', 'Compute Engine'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/paths/420',
    },
    {
      id: 'manage-kubernetes-in-gcp',
      title: 'Manage Kubernetes in Google Cloud',
      description: 'Dive deeper into managing GKE clusters. This course covers monitoring, logging, and managing applications in a production environment.',
      duration: '7 Hours',
      difficulty: 'Advanced',
      tags: ['GKE', 'Kubernetes', 'DevOps'],
      thumbnailUrl: 'https://cdn.qwiklabs.com/gFmqBw+OuxgbiL0lz4P6jAQ57ywaL4ecCKO4N4BIfgI=',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/634',
    },
    {
      id: 'getting-started-with-cloud-storage',
      title: 'Getting Started with Cloud Storage',
      description: 'Learn the fundamentals of Google Cloud Storage, including creating buckets, uploading objects, and managing access control.',
      duration: '3 Hours',
      difficulty: 'Beginner',
      tags: ['GCP', 'Storage'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/641',
    },
    {
      id: 'serverless-cloud-run-development',
      title: 'Serverless Cloud Run Development',
      description: 'Learn how to deploy and manage serverless applications on Google Cloud Run, a fully managed compute platform.',
      duration: '5 Hours',
      difficulty: 'Intermediate',
      tags: ['Serverless', 'Cloud Run', 'GCP'],
      thumbnailUrl: 'https://logodix.com/logo/433040.jpg',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/761',
    },
    {
      id: 'introduction-to-generative-ai',
      title: 'Introduction to Generative AI',
      description: 'A foundational course covering the basics of what Generative AI is, how it is used, and how it differs from traditional machine learning methods.',
      duration: '4 Hours',
      difficulty: 'Beginner',
      tags: ['GenAI', 'AI', 'Vertex AI'],
      thumbnailUrl: 'https://logowik.com/content/uploads/images/google-ai-gemini91216.logowik.com.webp',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/966',
    },
    {
      id: 'introduction-to-large-language-models',
      title: 'Introduction to Large Language Models',
      description: 'Explore the fundamentals of Large Language Models (LLMs), their use cases, and how you can tune them for your specific needs.',
      duration: '4Hours',
      difficulty: 'Beginner',
      tags: ['LLM', 'AI', 'Prompt Engineering'],
      thumbnailUrl: 'https://logowik.com/content/uploads/images/google-ai-gemini91216.logowik.com.webp',
      courseUrl: 'https://www.cloudskillsboost.google/course_templates/976',
    },
    {
      id: 'build-apps-with-google-workspace-apis',
      title: 'Build Apps with Google Workspace APIs',
      description: 'Learn to use Google Workspace APIs to build applications that integrate with services like Gmail, Drive, Calendar, and Sheets.',
      duration: '10 Hours',
      difficulty: 'Intermediate',
      tags: ['Workspace', 'API', 'Automation'],
      thumbnailUrl: 'https://logowik.com/content/uploads/images/4192-google-workspace.webp',
      courseUrl: 'https://www.cloudskillsboost.google/paths/1282',
    }
  ];
  
